name: 'Create a workflow dispatch event'
description: 'You can use workflow dispatch event to manually trigger a GitHub Actions workflow run.'
inputs:
  token:
    description: 'The access token with the repo scope.'
    required: true
  repository:
    description: 'The workflow repository.'
    required: true
  workflow-id:
    description: 'The ID of the workflow. You can also pass the workflow file name as a string.'
    required: true
  ref:
    description: 'The git reference for the workflow. The reference can be a branch or tag name.'
    required: true
    default: 'main'
  inputs:
    description: 'Input keys and values configured in the workflow file. The maximum number of properties is 10. Any default properties configured in the workflow file will be used when inputs are omitted.'
    required: true
    default: ''
runs:
  using: "composite"
  steps: 
    - run: |
        curl -X POST -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ inputs.token }}" \
        -d '{"ref":"${{ inputs.ref }}", "inputs":{${{ inputs.inputs }}}}' \
        https://api.github.com/repos/${{ inputs.repository }}/actions/workflows/${{ inputs.workflow-id }}/dispatches
      shell: bash
